sudo: required
language: ruby
rvm:
- 2.4.4
cache: bundler
services:
- docker
script:
- echo "no tests ¯\_(ツ)_/¯ this is just for CD"
after_success:
- provisioning/travis_ci_and_cd/build_and_push_to_ecr.sh
branches:
  only:
  - master
env:
  global:
  - secure: OPkx7hJCAhMDFUaoIgGTjjem4EIaQ/byQnpN9+3fhCyMderXjTGFvR04qgbrGBfYZyiD0VyZdaY+aeXPbt09K6S/39WAK1IPoAIDJqPjWdiJyoztQ8xb4NbwyNMkkgZpMjQsMJIIjjQXAxGSe+jg/7yrzCmRUs8gHdBmRzvtdIn8nKCOD1eORJASL7l6vxV8lV9/63nTn3s2oFtjQZ1/PLixegOSSGClQPnFJGQFxHtW5BzqhFpM2a9BTBTvUMfm8aTaOepWaZ0o9sDViwdQOFcJ2wx/lol07+dS4+s4zG1hrFk+Yg08niPDA4VMKTtWiZ5PThTLsGbBYamCt6cQGA61LhFPvFI9VdnQh5Z8kQMcW2O06x+hHdEKZA4hyVcgoA4g7DA/DE3G8gctNkn4taHojVIC52HTKNXdMejo4p+Oehl3E6svnywnkse/2G4P0so0rC44X7MIB5Ul6g33Bqmii3i0ysuJ8hXVPbV4n8XDyGK4SBfCXirFAmxrf71IvITe5LrcRNAUPQp8FKAhE4f+vBuPaRxNCnw1ZPZJWaU4bJebdp0lsnZzyw2eCS+hQICn2gmZA9llw2kMOqR5RKQicrKzuEk1M+7ELQWNLcI8LrLaCGceJCAl5k052GiA9laXkc5NnL60D6kQmMebSs8AtX0MAl0sPiXNcqj4Gi8=
  - secure: EVmvxhrxYh7cdlIGaEBEwlcW6XozBjguikF4E0N+MMKaQo2GDbrb9008PlCyNi4uXhWSZrfVzU2OJWXNY4ZApJf+I9dztBqKYTIYpVVgkUA0BxJDyt7Y+ViWAWR46F+YyCxqVORRMVQl5WWti42kmmvssD6OI96EqFZuhCsQUtkS0qAelBjDCgJaE5TZhKQWetIpDYSfu7khjTX6pz9Afm7JIFhhWktcMimBl6stzQK2umnGdoklhR+gG83nChEj1+hTeYtoez/eCRaoFSZ2Vin6d85AEcWRCTsejpm0dsZgpGlYV6kstQQ4TLmT24OEwxZoIWkKPdo4P41xegALvFIb4+UUhxAdKgs+6p6IZi8Wq4oFTHpyuO+YXZjkbO/CJ2+6696TZPE3SG07jc1G+fKzsm7vKYAymVnONthb48yPCqbJNv98X6bqkxV9TXbyBvV8xuhk6C+EOZDE9h+3PISp395ffGuXw1b8Biw4seOC15UJrc0ijOR8o6Y9nDbcXlokkmZzGrDAD2Xh+I4rZj2IzpAeTWROIR/Gfojr/LQCMwH+5y3sHrxFST8ue80VZVmYJ6cAIY69FshaLAhR8Xmt+/SwXrm3CMPfdrUi+w6TYn41CJ/x/yhNODCUZyPFODbJPXUDvNsmCNuF/XM6ORS/rby2pEC0mNXDbEeVHOc=
  - secure: maWC7qOkbd6dsg93zPOOlUKRefzUUo0ws6D30xKZluTzI8EG7IPzdD68fu0/viodc6c7xa9aQsYTLbUCWEy2eIr91N/nAKg+b/r5uUUCY4KeXfs4AbXtIDW3u5JHUbqdhfSAjXgqQ7a8qERMco3bfvo96ICy7atrennpuyYCzcFcNzhH6lRyn3m1Ai9NKzM6BuDSEwUDKC1vrSL8yepO0AxuRAvFaQ1x2dgGXxEugFD/Np+5D3CG8KAmd1fs98x7IUXb74JXgrWNkIjRWy4JsI0VzFI5GV+vTWDjsZB/LAsW845qD8HwJvaNrL6WC41sV+UDgF5Q/c2jiBOsik0qlr1BYqpamzK682MhU+Rukt70qtAhVb7Uz2WWQVLUY8VMlxS0F7BD0Ly8qmLuWCn5C/8J0cIKXg1QGVbcCX1OkgQq5rQ5zFuxILdrfx7M7BCpCtVP5cvQFA4mfHsCLVwe9Nrilg+Bo5L6Gg22w8Pl4x6B+Lu5ZoZPQicMKCgYsBgLzQcWb8tHQC1sBEgHk+1WVPnYazmu3vzSAg+Vjh3Abh8+++ei9s3GIg6H1XSXy5Rmd8qhfsfW1PYijnxYbktxMTAHdm9icBWtSSZaf/Jfs0c0cRwzoJJgnLAWQBuFXumwYxGzcNEYLUK7lhkx9gX23+FcER7ksyumPOsqu5wt8Lo=
