version: '3.4'
services:
  gateway_exporter:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file:
      - ./.env
    volumes:
      - '.:/opt/api_gateway_exporter'
