# 1.  This sets sensible build args.
# 2.  The value of SSH_PRIVATE_KEY is nonsense though in development we mount your local
#     ~/.ssh to the container's to use the developer's private key.
# 3.  This also mounts pwd into the container so you can develop locally, but test inside the container.
version: '3.4'
services:
  gateway_exporter:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        SSH_PRIVATE_KEY: dGhpcy1tZWFucy1ub3RoaW5nLWluLWRldmVsb3BtZW50LXlvdXItc3NoLWRpci13aWxsLW1vdW50LXRvLXRoZS1jb250YWluZXIK
        GIT_USERNAME: nypl/api_gateway_exporter
        GIT_USER_EMAIL: api_gateway_exporter@nypl.org
    env_file:
      - ./.env
    volumes:
      - '.:/opt/api_gateway_exporter'
      - '~/.ssh:/root/.ssh'
