version: '3.4'
services:
  gateway_exporter:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        - SSH_PRIVATE_KEY="dGhpcy1tZWFucy1ub3RoaW5nLWluLWRldmVsb3BtZW50LXlvdXItc3NoLWRpci13aWxsLW1vdW50LXRvLXRoZS1jb250YWluZXIK"
    env_file:
      - ./.env
    volumes:
      - '.:/opt/api_gateway_exporter'
      - '~/.ssh:/root/.ssh'
